[2023-12-07 16:31:02,943] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.179:5000 (Press CTRL+C to quit) - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:31:05,719] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:31:05] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:31:05,892] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:31:05] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:31:06,434] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:31:06] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:31:06,542] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:31:06] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:31:06,558] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:31:06] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:31:08,876] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:31:08] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:31:08,941] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:31:08] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:31:08,985] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:31:08] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:31:08,988] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:31:08] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:31:09,560] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:31:09] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:31:14,011] ERROR log_exception() L1449 Exception on /avaliacao [POST] - call_trace=C:\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\mvp-qualidade-seguranca-sistemas-inteligentes\exemplo_mvp\api\app.py", line 74, in predict
    modelo = Model.treinar_KNN(ml_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Model.treinar_KNN() missing 2 required positional arguments: 'X_train' and 'Y_train'
[2023-12-07 16:31:14,042] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:31:14] "[35m[1mPOST /avaliacao HTTP/1.1[0m" 500 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:34:44,982] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.179:5000 (Press CTRL+C to quit) - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:35:34,051] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.179:5000 (Press CTRL+C to quit) - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:35:36,857] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:35:36] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:35:37,141] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:35:37] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:35:37,721] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:35:37] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:35:37,742] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:35:37] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:35:37,769] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:35:37] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:35:39,235] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:35:39] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:35:39,282] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:35:39] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:35:39,348] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:35:39] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:35:39,349] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:35:39] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:35:39,921] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:35:39] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:35:45,058] ERROR log_exception() L1449 Exception on /avaliacao [POST] - call_trace=C:\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\mvp-qualidade-seguranca-sistemas-inteligentes\exemplo_mvp\api\app.py", line 77, in predict
    dataset = Carregador().carregar_dados(ml_path)
              ^^^^^^^^^^
NameError: name 'Carregador' is not defined
[2023-12-07 16:35:45,076] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:35:45] "[35m[1mPOST /avaliacao HTTP/1.1[0m" 500 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:41:34,793] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.179:5000 (Press CTRL+C to quit) - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:41:38,623] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:41:38] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-07 16:41:38,873] INFO _log() L224  127.0.0.1 - - [07/Dec/2023 16:41:38] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L224 
